import styles from '../styles/Generate.module.css';
import Head from 'next/head';
import ColorCard from '../components/ColorCard/ColorCard';
import { useState } from 'react';

const NUMBERCARDS = 5;


function generateColor()
{
  var letters = '0123456789ABCDEF';
  var color = '#';
  let colors = [];
  //TODO Change number of color cards to prop
  for(let j = 0; j < NUMBERCARDS; j++)
  {
    for (var i = 0; i < 6; i++) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    colors.push(color);
    color = '#';
  }
  console.log(colors)
  return colors;
  
}

export default function Generate() {
  
  const [colors, setColors] = useState(generateColor()); 
  

  function rotateColors() {
    // window.location.reload(false);
    setColors(generateColor());
  }
   
    return (
        <div className={styles.container}>
          <Head>
        <title>Color Palette App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className="d-flex justify-content-between">
          {colors.map((item) =>{ 
            return(<ColorCard locked={false} color={item}/>)
          } )
        }
          </div>
          <button onClick={rotateColors} className='btn btn-info'>Generate New Set</button>
      
        
      </main>
        </div>
    )
};