import styles from '../styles/Generate.module.css';
import Head from 'next/head';
import ColorCard from '../components/ColorCard/ColorCard';

function refreshPage() {
    window.location.reload(false);
  }

export default function Generate() {
    return (
        <div className={styles.container}>
          <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className="d-flex justify-content-between">
          <ColorCard/>
        <ColorCard/>
        <ColorCard/>
        <ColorCard/>
        <ColorCard/>
          </div>
          <button onClick={refreshPage} className='btn btn-info'>Generate New Set</button>
      
        
      </main>
        </div>
    )
};